[package]
name = "rust-markdown-to-html"
version = "0.1.0"
authors = ["Adrian Cruz <drincruz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.7"
